import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { PostCard,type PublicPost } from "@/components/post-card";

export default async function Home(){
 const supabase=await createClient();
 const {data}=await supabase.from("posts").select("id,title,body,subject_name,category,source_url,created_at,profiles(display_name,username)").eq("status","published").order("created_at",{ascending:false}).limit(3);
 const posts=(data??[]) as unknown as PublicPost[];
 return <main><section className="hero"><div className="hero-copy"><p className="eyebrow">Openbaar onderzoeksplatform</p><h1>Macht wordt pas zichtbaar wanneer mensen <em>durven vastleggen.</em></h1><p className="lead">Vardena brengt controleerbare informatie over politici, bekende personen en andere invloedrijke figuren samen — met bronnen, context en ruimte voor correctie.</p><div className="hero-actions"><Link className="button" href="/feed">Bekijk berichten</Link><Link className="button ghost" href="/signup">Maak een account</Link></div></div><aside className="hero-panel"><span>01</span><h2>Geen losse beschuldigingen.</h2><p>Ieder bericht heeft een openbare bron nodig. Feiten, interpretatie en mening blijven herkenbaar gescheiden.</p><div className="panel-line"><b>Bron</b><b>Context</b><b>Wederhoor</b></div></aside></section><section className="statement"><p>Vardena is geen rechtbank.</p><h2>Het is een geheugen voor publieke verantwoordelijkheid.</h2></section><section className="latest" id="onderzoek"><div className="section-head"><div><p className="eyebrow">Nieuw op Vardena</p><h2>Recente berichten</h2></div><Link className="text-link" href="/feed">Bekijk alles →</Link></div>{posts.length?<div className="post-grid">{posts.map(post=><PostCard key={post.id} post={post}/>)}</div>:<div className="empty-state"><span>Het archief is klaar.</span><h3>Het eerste onderbouwde bericht kan nu worden geplaatst.</h3><Link className="button" href="/signup">Begin met bijdragen</Link></div>}</section><section className="method" id="werkwijze"><div><p className="eyebrow">De norm</p><h2>Vrij spreken vraagt verantwoordelijkheid.</h2></div><ol><li><b>01</b><div><strong>Maak de claim precies</strong><p>Beschrijf wat aantoonbaar is, zonder iemand schuldig te verklaren.</p></div></li><li><b>02</b><div><strong>Voeg de bron toe</strong><p>Een controleerbare https-link is verplicht bij ieder bericht.</p></div></li><li><b>03</b><div><strong>Laat correctie toe</strong><p>Nieuwe informatie en wederhoor kunnen een bericht aanvullen of corrigeren.</p></div></li></ol></section><section className="join"><p className="eyebrow">Doe mee</p><h2>Maak invloed controleerbaar.</h2><p>Open een account, verzamel bronnen en leg vast wat publiek relevant is.</p><Link className="button light" href="/signup">Account maken</Link></section></main>;
}
