import Link from "next/link";
import type { SupabaseClient } from "@supabase/supabase-js";
import { ActionForm,OrganizationForm } from "./organization-forms";
import { OrganizationChecklist } from "./organization-checklist";
import { Avatar } from "./social-icon";
import { createAssignment,createOrganizationPost,manageMembership,removeAssignment } from "@/app/organization-actions";
import { isManager,orgMemberFields,roleLabels,type Assignment,type Organization,type OrgMember } from "@/lib/organization-types";

type Context={supabase:SupabaseClient;org:Organization;membership:OrgMember};
export async function GroupOverview({supabase,org,membership,pending}:{pending:number}&Context){
  const [members,orgLikes,postStats,tasks,recent]=await Promise.all([
    supabase.from("vardena_org_members").select("user_id",{count:"exact",head:true}).eq("org_id",org.id).eq("status","active"),
    supabase.from("vardena_org_like_stats").select("likes").eq("org_id",org.id).maybeSingle(),
    supabase.from("vardena_org_post_stats").select("posts,likes,dislikes").eq("organization_id",org.id).maybeSingle(),
    supabase.from("vardena_org_assignments").select("id",{count:"exact",head:true}).eq("org_id",org.id),
    supabase.from("vardena_org_members").select("user_id,display_name,role,created_at").eq("org_id",org.id).eq("status","active").order("created_at",{ascending:false}).limit(5),
  ]);
  if([members,orgLikes,postStats,tasks,recent].some(r=>r.error))throw new Error("Groepsoverzicht laden lukt niet.");
  const base=`/organisaties/${org.slug}/groep`;
  return <section className="social-panel"><div className="org-stat-grid"><Link href={`${base}?tab=leden`}><b>{members.count??0}</b><span>Leden</span></Link><div><b>{orgLikes.data?.likes??0}</b><span>Likes voor organisatie</span></div><div><b>{postStats.data?.likes??0}</b><span>Likes op berichten</span></div><div><b>{postStats.data?.dislikes??0}</b><span>Dislikes op berichten</span></div><Link href={`${base}?tab=opdrachten`}><b>{tasks.count??0}</b><span>{isManager(membership.role)?"Opdrachten & uitdagingen":"Mijn opdrachten"}</span></Link>{isManager(membership.role)?<Link href={`${base}?tab=aanmeldingen`}><b>{pending}</b><span>Nieuwe aanmeldingen</span></Link>:<Link href={`/organisaties/${org.slug}`}><b>{postStats.data?.posts??0}</b><span>Publicaties</span></Link>}</div>
    <h2>Jullie werkplek</h2><p>Overleg in de groepschat, vind andere leden en werk aan opdrachten met een eigen checklist.</p><div className="org-actions"><Link className="button small" href={`${base}?tab=chat`}>Open groepschat</Link><Link className="button small ghost" href={`${base}?tab=opdrachten`}>Bekijk opdrachten</Link></div>
    <h3>Nieuwste leden</h3><div className="org-recent-members">{recent.data?.map(m=><div key={m.user_id}><Avatar name={m.display_name}/><span><strong>{m.display_name}</strong><small>{roleLabels[m.role as keyof typeof roleLabels]}</small></span></div>)}</div>
    <aside className="org-workflow"><h3>Van vraag naar openbare bijdrage</h3><ol><li>Kies een concrete claim of vraag.</li><li>Verzamel oorspronkelijke bronnen en context.</li><li>Verdeel het onderzoek in persoonlijke stappen.</li><li>Laat een beheerder de onderbouwde bijdrage publiceren.</li></ol></aside>
  </section>;
}

export async function GroupMembers({supabase,org,membership,page,requests=false,search=""}:Context&{page:number;requests?:boolean;search?:string}){
  let query=supabase.from("vardena_org_members").select(orgMemberFields,{count:"exact"}).eq("org_id",org.id).eq("status",requests?"pending":"active");
  const term=search.replace(/[^\p{L}\p{N} -]/gu,"").slice(0,80);if(term)query=query.ilike("display_name",`%${term}%`);
  const result=await query.order("created_at",{ascending:false}).order("user_id").range((page-1)*30,page*30-1);
  if(result.error)throw new Error("Leden laden lukt niet.");
  const members=(result.data??[]) as OrgMember[],tab=requests?"aanmeldingen":"leden",base=`/organisaties/${org.slug}/groep`;
  return <section className="social-panel"><h2>{requests?"Nieuwe aanmeldingen":"Leden van de groep"}</h2><p>{requests?"Keur een aanvraag goed om toegang tot de groep te geven.":"Alleen toegelaten leden kunnen deze lijst bekijken."}</p><form className="people-search inline-search" action={base}><input type="hidden" name="tab" value={tab}/><label className="sr-only" htmlFor="member-search">Zoek op naam</label><input id="member-search" name="zoek" defaultValue={search} placeholder="Zoek op naam" maxLength={80}/><button className="button small ghost">Zoeken</button></form>
    {members.length?members.map(member=><article className="org-member-row" key={member.user_id}><div className="org-member-identity"><Avatar name={member.display_name}/><div><strong>{member.display_name}{member.user_id===membership.user_id?" (jij)":""}</strong><small>{requests?`Aangemeld op ${new Date(member.created_at).toLocaleDateString("nl-NL",{timeZone:"Europe/Amsterdam"})}`:roleLabels[member.role]}</small></div></div><div className="org-member-controls">{requests?<><ActionForm compact action={manageMembership.bind(null,org.id,member.user_id,"approve")} label="Toelaten"/><ActionForm compact action={manageMembership.bind(null,org.id,member.user_id,"reject")} label="Afwijzen" confirm={`Aanmelding van ${member.display_name} afwijzen?`}/></>:<>{membership.role==="owner"&&member.role!=="owner"?<ActionForm compact action={manageMembership.bind(null,org.id,member.user_id,member.role==="admin"?"demote":"promote")} label={member.role==="admin"?"Maak lid":"Maak beheerder"} confirm={member.role==="admin"?`Beheerdersrechten van ${member.display_name} intrekken?`:`${member.display_name} beheerder maken? Deze persoon kan aanmeldingen, opdrachten en publicaties beheren.`}/>:null}{member.role!=="owner"&&member.user_id!==membership.user_id&&(membership.role==="owner"||(membership.role==="admin"&&member.role==="member"))?<ActionForm compact action={manageMembership.bind(null,org.id,member.user_id,"remove")} label="Verwijderen" confirm={`${member.display_name} uit de groep verwijderen?`}/>:null}</>}</div></article>):<div className="social-empty"><p>{requests?"Geen openstaande aanmeldingen.":"Geen leden gevonden."}</p></div>}
    <nav className="social-pagination" aria-label="Ledenpagina’s">{page>1?<Link href={`${base}?tab=${tab}&zoek=${encodeURIComponent(search)}&pagina=${page-1}`}>← Vorige</Link>:<span/>}{(result.count??0)>page*30?<Link href={`${base}?tab=${tab}&zoek=${encodeURIComponent(search)}&pagina=${page+1}`}>Volgende →</Link>:null}</nav>
    {!requests&&membership.role!=="owner"?<details className="org-leave"><summary>Groep verlaten</summary><p>Je verliest toegang tot de chat en opdrachten. Eerdere groepsberichten blijven staan.</p><ActionForm compact action={manageMembership.bind(null,org.id,membership.user_id,"leave")} label="Verlaat deze groep" confirm="Wil je deze groep verlaten?"/></details>:null}
  </section>;
}

export async function GroupAssignments({supabase,org,membership,page,memberSearch=""}:Context&{page:number;memberSearch?:string}){
  const manager=isManager(membership.role),base=`/organisaties/${org.slug}/groep`;
  const result=await supabase.from("vardena_org_assignments").select("id,assignee_id,title,description,kind,due_date,created_at,vardena_org_checklist(id,label,position,completed)",{count:"exact"}).eq("org_id",org.id).order("created_at",{ascending:false}).order("id",{ascending:false}).range((page-1)*20,page*20-1);
  if(result.error)throw new Error("Opdrachten laden lukt niet.");
  const assignments=(result.data??[]) as unknown as Assignment[],ids=[...new Set(assignments.map(a=>a.assignee_id))];
  const names=ids.length?await supabase.from("vardena_org_members").select("user_id,display_name").eq("org_id",org.id).in("user_id",ids):{data:[],error:null};
  let membersQuery=supabase.from("vardena_org_members").select("user_id,display_name").eq("org_id",org.id).eq("status","active");
  const term=memberSearch.replace(/[^\p{L}\p{N} -]/gu,"").slice(0,80);if(term)membersQuery=membersQuery.ilike("display_name",`%${term}%`);
  const members=manager?await membersQuery.order("display_name").limit(50):{data:[],error:null};
  if(names.error||members.error)throw new Error("Namen bij opdrachten laden lukt niet.");
  const byId=new Map((names.data??[]).map(m=>[m.user_id,m.display_name]));
  return <section className="social-panel"><h2>{manager?"Opdrachten & uitdagingen":"Mijn opdrachten & uitdagingen"}</h2><p>Elke opdracht is persoonlijk. Het toegewezen lid vinkt de stappen af; beheerders zien de voortgang.</p>
    {manager?<details className="org-create-assignment" open={Boolean(memberSearch)}><summary>+ Opdracht of uitdaging toewijzen</summary><form className="people-search inline-search" action={base}><input type="hidden" name="tab" value="opdrachten"/><label className="sr-only" htmlFor="assignee-search">Zoek een lid voor een opdracht</label><input id="assignee-search" name="lid" defaultValue={memberSearch} placeholder="Zoek een lid (eerste 50 worden getoond)" maxLength={80}/><button className="button small ghost">Zoeken</button></form><ActionForm action={createAssignment.bind(null,org.id)} label="Toewijzen aan lid" reset><div className="form-row"><label>Voor wie?<select name="assignee" required defaultValue=""><option value="" disabled>Kies een lid</option>{members.data?.map(member=><option value={member.user_id} key={member.user_id}>{member.display_name}</option>)}</select></label><label>Soort<select name="kind"><option value="task">Opdracht</option><option value="challenge">Uitdaging</option></select></label></div><label>Titel<input name="title" required minLength={3} maxLength={140} placeholder="Wat gaat dit lid doen?"/></label><label>Toelichting<textarea name="description" rows={3} maxLength={2000}/></label><label>Afvinkbare stappen<textarea name="steps" required rows={5} maxLength={4020} placeholder={"Eén stap per regel\nVoeg de oorspronkelijke bron toe\nControleer datum en context"}/><small>1–20 stappen, maximaal 200 tekens per stap.</small></label><label>Streefdatum (optioneel)<input name="dueDate" type="date"/></label></ActionForm></details>:null}
    <div className="org-assignments">{assignments.length?assignments.map(assignment=><article className="org-assignment" key={assignment.id}><div className="org-assignment-heading"><span className="topic-pill">{assignment.kind==="challenge"?"Uitdaging":"Opdracht"}</span><small>Voor {byId.get(assignment.assignee_id)??"voormalig lid"}</small></div><h3>{assignment.title}</h3>{assignment.description?<p>{assignment.description}</p>:null}{assignment.due_date?<p className="small-copy muted">Streefdatum: {new Date(`${assignment.due_date}T12:00:00Z`).toLocaleDateString("nl-NL",{timeZone:"Europe/Amsterdam"})}</p>:null}<OrganizationChecklist key={`${assignment.id}:${assignment.vardena_org_checklist.map(i=>`${i.id}${i.completed}`).join()}`} items={assignment.vardena_org_checklist} editable={assignment.assignee_id===membership.user_id}/>{manager?<ActionForm compact action={removeAssignment.bind(null,assignment.id)} label="Opdracht verwijderen" confirm="Deze opdracht en checklist verwijderen?"/>:null}</article>):<div className="social-empty"><h3>Nog geen opdrachten.</h3><p>{manager?"Wijs hierboven de eerste opdracht of uitdaging toe.":"Je beheerder kan hier opdrachten voor je klaarzetten."}</p></div>}</div>
    <nav className="social-pagination" aria-label="Opdrachtpagina’s">{page>1?<Link href={`${base}?tab=opdrachten&pagina=${page-1}`}>← Vorige</Link>:<span/>}{(result.count??0)>page*20?<Link href={`${base}?tab=opdrachten&pagina=${page+1}`}>Volgende →</Link>:null}</nav>
  </section>;
}

export function GroupPublish({org}:{org:Organization}){
  return <section className="social-panel"><h2>Publiceer namens {org.name}</h2><p>Dit bericht verschijnt openbaar onder de organisatienaam, met een link naar jullie profiel.</p><ActionForm action={createOrganizationPost.bind(null,org.id)} label="Openbaar publiceren" pendingLabel="Publiceren…"><div className="form-row"><label>Over wie?<input name="subjectName" required minLength={2} maxLength={120}/></label><label>Categorie<select name="category"><option value="politiek">Politiek</option><option value="media">Media</option><option value="bedrijfsleven">Bedrijfsleven</option><option value="overig">Overig</option></select></label></div><label>Titel<input name="title" required minLength={5} maxLength={140}/></label><label>Bericht<textarea name="body" required minLength={20} maxLength={3000} rows={7}/></label><label>Openbare bron<input type="url" name="sourceUrl" required maxLength={2048} placeholder="https://…"/></label><p className="small-copy muted">Maak duidelijk wat de bron aantoont en welke onzekerheden er zijn. Een bron of veel likes maakt een claim niet automatisch waar.</p></ActionForm></section>;
}
export function GroupSettings({org}:{org:Organization}){return <section className="social-panel"><h2>Openbaar organisatieprofiel</h2><OrganizationForm organization={org}/></section>;}
