import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { createPost } from "@/app/actions";
import { PostCard,type PublicPost } from "@/components/post-card";
type Props={searchParams:Promise<{error?:string;message?:string}>};
export default async function FeedPage({searchParams}:Props){
 const params=await searchParams,supabase=await createClient();
 const [{data:auth},{data}]=await Promise.all([supabase.auth.getClaims(),supabase.from("posts").select("id,title,body,subject_name,category,source_url,created_at,profiles(display_name,username)").eq("status","published").order("created_at",{ascending:false})]);
 const signedIn=Boolean(auth?.claims?.sub),posts=(data??[]) as unknown as PublicPost[];
 return <main className="feed-page"><section className="feed-intro"><p className="eyebrow">Openbaar archief</p><h1>Berichten en bronnen</h1><p>Bijdragen van leden. Een bron maakt een claim controleerbaar; niet automatisch waar.</p>{!signedIn&&<Link className="button" href="/login">Log in om te plaatsen</Link>}</section>{params.error&&<p className="notice error">{params.error}</p>}{params.message&&<p className="notice success">{params.message}</p>}{signedIn&&<section className="composer" id="nieuw"><div><p className="eyebrow">Nieuw bericht</p><h2>Leg iets vast</h2><p>Schrijf feitelijk, wees precies en voeg de beste openbare bron toe.</p></div><form action={createPost}><div className="form-row"><label>Over wie?<input name="subjectName" required minLength={2} placeholder="Naam van de publieke persoon"/></label><label>Categorie<select name="category" defaultValue="politiek"><option value="politiek">Politiek</option><option value="media">Media</option><option value="bedrijfsleven">Bedrijfsleven</option><option value="overig">Overig</option></select></label></div><label>Titel<input name="title" required minLength={5} maxLength={140} placeholder="Wat moet worden onderzocht?"/></label><label>Toelichting<textarea name="body" required minLength={20} maxLength={3000} rows={7} placeholder="Beschrijf de gebeurtenis en context…"/></label><label>Openbare bron<input name="sourceUrl" type="url" required placeholder="https://…"/></label><div className="form-foot"><small>Alleen publiek relevante, controleerbare informatie.</small><button className="button" type="submit">Publiceer bericht</button></div></form></section>}<section className="feed-list"><div className="section-head"><div><p className="eyebrow">Alle bijdragen</p><h2>{posts.length} berichten</h2></div></div>{posts.length?<div className="post-grid">{posts.map(post=><PostCard key={post.id} post={post}/>)}</div>:<div className="empty-state"><h3>Nog geen berichten.</h3><p>Het eerste bericht kan na het koppelen van Supabase worden geplaatst.</p></div>}</section></main>;
}
